### PR TITLE
A2 gamestart

### LINKED ISSUE #30: A2 game start
**Provide a group of C++ classes that implements a user interaction mechanism to start the game by
allowing the player to:**
1) Select a map from a list of files as stored in a directory (e.g., rectangular, L, shapes)
2) Select 2 players’ game.
The code should: (a) load all the game pieces and use the map loader to load the selected and
appropriate map; (b)create the two players with the implemented exchange () method that allows
the player to select the card from its position in the row and pay the coin cost listed at the top of
the board (see the game rules for details); (d) assign biding facility to each player; (e) create a deck
of cards; and (f) create the game armies, token and cities.
**Requirements part 1: You must deliver a driver that demonstrates:**
• The different valid maps can be loaded and their validity is verified (i.e., it is a connected graph,
etc.), and invalid maps are rejected without the program crashing.
• A two game players is created.
• An assigned deck with the number of cards created.
• An assigned biding facility to each player.
• The game’s components: armies, token, and cities.

### PR DESCRIPTION
**Pull request by jaforte**

### CODE REVIEW

File: EightMinuteEmpireLegends/Core/GameCore/GameCore.cpp [hunk 1]
```diff
@@ -0,0 +1,103 @@
...
+Game::~Game() {	
+	delete this->map;	
+	for (Player* pl : this->players) {
+		delete pl;
+	}
+}
+
+// Gamebuilder class implementation. 
+
+Game* GameBuilder::build(int numPlayers, Map& map, std::string path) {
```
Comment (joshpham97) [inline EightMinuteEmpireLegends/Core/GameCore/GameCore.cpp]: As discussed, the logic to load the map should be in the build method because it is part of the creation logic.  We also need to let the players select their player names. The options I proposed to Jason is to pass the map path as a string (instead of a map object) to the builder and a list of player names to the build() method. 

The player input can either be handled in the main game (so we have separation of user input and game creation), or we can over load the build() method with (1) a build method that excepts no params and let player selects map, player names and (2) a build method with params that builds the game object. (1) will call (2) once user input is completed.

File: EightMinuteEmpireLegends/Core/GameBuilderException.h [hunk 2]
```diff
@@ -0,0 +1,12 @@
+#pragma once
+
+#include "../pch.h"
+
+class GameBuilderException : public std::exception
```
Comment (jonZlotnik) [inline EightMinuteEmpireLegends/Core/GameBuilderException.h]: I think you meant to delete this file. Seems to be a duplicate of the one in Core/GameCore dir

**Review by jonZlotnik — CHANGES_REQUESTED** [review]
Good work. Just remove that file, then I think it's ready to merge.

**Review by joshpham97 — CHANGES_REQUESTED** [review]

File: EightMinuteEmpireLegends/Core/GameCore/GameCore.cpp (hunk 1 above)
Comment (jaforte) [reply EightMinuteEmpireLegends/Core/GameCore/GameCore.cpp]: Just as a reminder to myself, I'd also like to add an operator overload for << in Game which will call the << function for all its members. Will be useful for debugging

**Review by jonZlotnik — DISMISSED** [review]
Further changes can be made in a new branch. (like adding your stream operator)

**Review by joshpham97 — APPROVED** [review]
